"#version 110\n"

"vec4 hsvToRgb(in vec4 hsva) {\n"
	"vec4 res;\n"
	"res.w = hsva.w;\n"
	"int i;\n"
	"float f, p, q, t;\n"
	"if (hsva.y == 0.f) {\n"
		"res.x = res.y = res.z = hsva.z;\n"
		"return res;\n"
	"}\n"
	"float h = hsva.x * 360.f;\n"
	"h /= 60.f;\n"
	"i = int(floor(h));\n"
	"f = h - float(i);"
	"p = hsva.z * (1.f - hsva.y);"
	"q = hsva.z * (1.f - hsva.y * f);"
	"t = hsva.z * (1.f - hsva.y * (1.f - f));"
	"if (i == 0) {"
		"res.x = hsva.z;"
		"res.y = t;"
		"res.z = p;"
	"}"
	"if (i == 1) {"
		"res.x = q;"
		"res.y = hsva.z;"
		"res.z = p;"
	"}"
	"if (i == 2) {"
		"res.x = p;"
		"res.y = hsva.z;"
		"res.z = t;"
	"}"
	"if (i == 3) {"
		"res.x = p;"
		"res.y = q;"
		"res.z = hsva.z;"
	"}"
	"if (i == 4) {"
		"res.x = t;"
		"res.y = p;"
		"res.z = hsva.z;"
	"}"
	"if (i == 5) {"
		"res.x = hsva.z;"
		"res.y = p;"
		"res.z = q;"
	"}"

	"return res;"
"}"

"void main(void) {"
	"gl_FragColor = hsvToRgb(gl_Color);"
"}"